#-------------------------------
# General Site Settings
title: Metabig Blog
# logo: logo.svg # You can add own logo.
description: Zolan is modern minimal theme for Jekyll


#-------------------------------
# Author Settings
author:
  name: Antoni Bergas
  image: 11.jpg
  say-hello: Hello, I’m <strong>Antoni Bergas</strong>
  bio: Hacker wannabe, computer engineering student, passionate about technology. Currently working and studying at Universitat Politècnica de Catalunya.


#-------------------------------
# Contact links
instagram: https://www.instagram.com/tonibergas/ # Add your Instagram handle


#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: tonibergas # Add instagram username